% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Assignment\_5\_Maric\_Räderer},
  pdfauthor={Akando Räderer - 23-615-669, Aleksandar Maric - 24-616-427},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Assignment\_5\_Maric\_Räderer}
\author{Akando Räderer - 23-615-669, Aleksandar Maric - 24-616-427}
\date{}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\section{Question 1: Descriptive
Analysis}\label{question-1-descriptive-analysis}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# download and clean data}

\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.2.0     v readr     2.2.0
## v forcats   1.0.1     v stringr   1.6.0
## v ggplot2   4.0.2     v tibble    3.3.1
## v lubridate 1.9.5     v tidyr     1.3.2
## v purrr     1.2.1     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(skimr)}

\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"education\_income{-}3.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 18490 Columns: 7
## -- Column specification --------------------------------------------------------
## Delimiter: ","
## dbl (7): id, year, college, income, scholarship, hhincome, race
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_clean }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}
    \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(id),}
    \SpecialCharTok{!}\FunctionTok{duplicated}\NormalTok{(id),}
\NormalTok{    year }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{2000}\NormalTok{, }\DecValTok{2010}\NormalTok{),}
\NormalTok{    college }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{),}
\NormalTok{    income }\SpecialCharTok{\textgreater{}=} \DecValTok{0}\NormalTok{,}
\NormalTok{    scholarship }\SpecialCharTok{\textgreater{}=} \DecValTok{0}\NormalTok{,}
\NormalTok{    hhincome }\SpecialCharTok{\textgreater{}=} \DecValTok{0}\NormalTok{,}
\NormalTok{    race }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{white =}\NormalTok{ race,}
    \AttributeTok{low\_income =} \FunctionTok{ifelse}\NormalTok{(hhincome }\SpecialCharTok{\textless{}} \FunctionTok{median}\NormalTok{(hhincome, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{  )}

\FunctionTok{skim}\NormalTok{(data\_clean)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule\noalign{}
\endfirsthead
\endhead
\bottomrule\noalign{}
\endlastfoot
Name & data\_clean \\
Number of rows & 16962 \\
Number of columns & 9 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
numeric & 9 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\end{longtable}

\textbf{Variable type: numeric}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1373}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0980}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.1373}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0784}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0784}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0784}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0784}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0784}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0882}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0882}}
  >{\raggedright\arraybackslash}p{(\linewidth - 20\tabcolsep) * \real{0.0588}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p0
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p25
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p75
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p100
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
hist
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
id & 0 & 1 & 9243.96 & 5341.38 & 1.00 & 4622.25 & 9242.50 & 13864.75 &
18490.00 & ▇▇▇▇▇ \\
year & 0 & 1 & 2005.02 & 5.00 & 2000.00 & 2000.00 & 2010.00 & 2010.00 &
2010.00 & ▇▁▁▁▇ \\
college & 0 & 1 & 0.74 & 0.44 & 0.00 & 0.00 & 1.00 & 1.00 & 1.00 &
▃▁▁▁▇ \\
income & 0 & 1 & 126.84 & 35.63 & 25.88 & 102.06 & 125.11 & 149.63 &
301.39 & ▂▇▅▁▁ \\
scholarship & 0 & 1 & 20.12 & 5.83 & 10.00 & 15.06 & 20.17 & 25.23 &
30.00 & ▇▇▇▇▇ \\
hhincome & 0 & 1 & 81.41 & 35.61 & 7.96 & 54.71 & 77.27 & 103.40 &
262.79 & ▅▇▃▁▁ \\
race & 0 & 1 & 0.80 & 0.40 & 0.00 & 1.00 & 1.00 & 1.00 & 1.00 & ▂▁▁▁▇ \\
white & 0 & 1 & 0.80 & 0.40 & 0.00 & 1.00 & 1.00 & 1.00 & 1.00 &
▂▁▁▁▇ \\
low\_income & 0 & 1 & 0.50 & 0.50 & 0.00 & 0.00 & 0.50 & 1.00 & 1.00 &
▇▁▁▁▇ \\
\end{longtable}
}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_clean }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{observations =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{duplicate\_ids =} \FunctionTok{sum}\NormalTok{(}\FunctionTok{duplicated}\NormalTok{(id)),}
    \AttributeTok{min\_year =} \FunctionTok{min}\NormalTok{(year),}
    \AttributeTok{max\_year =} \FunctionTok{max}\NormalTok{(year),}
    \AttributeTok{invalid\_college =} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\NormalTok{college }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{)),}
    \AttributeTok{min\_income =} \FunctionTok{min}\NormalTok{(income),}
    \AttributeTok{min\_scholarship =} \FunctionTok{min}\NormalTok{(scholarship),}
    \AttributeTok{min\_hhincome =} \FunctionTok{min}\NormalTok{(hhincome),}
    \AttributeTok{invalid\_race =} \FunctionTok{sum}\NormalTok{(}\SpecialCharTok{!}\NormalTok{race }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{)),}
    \AttributeTok{missing\_values =} \FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(.))}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 10
##   observations duplicate_ids min_year max_year invalid_college min_income
##          <int>         <int>    <dbl>    <dbl>           <int>      <dbl>
## 1        16962             0     2000     2010               0       25.9
## # i 4 more variables: min_scholarship <dbl>, min_hhincome <dbl>,
## #   invalid_race <int>, missing_values <int>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# calculate income means}
\NormalTok{income\_college }\OtherTok{\textless{}{-}}\NormalTok{ data\_clean }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(college }\SpecialCharTok{==} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{pull}\NormalTok{(income)}

\NormalTok{income\_non\_college }\OtherTok{\textless{}{-}}\NormalTok{ data\_clean }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(college }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{pull}\NormalTok{(income)}



\NormalTok{mean\_all }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(data\_clean}\SpecialCharTok{$}\NormalTok{income)}

\NormalTok{mean\_college }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(income\_college)}

\NormalTok{mean\_non\_college }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{ (income\_non\_college)}

\FunctionTok{print}\NormalTok{(mean\_all)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 126.842
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(mean\_college)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 137.7154
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(mean\_non\_college)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 96.20427
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mean\_difference }\OtherTok{\textless{}{-}}\NormalTok{ mean\_college }\SpecialCharTok{{-}}\NormalTok{ mean\_non\_college}

\FunctionTok{print}\NormalTok{(mean\_difference)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 41.51108
\end{verbatim}

-\textgreater{} explain \ldots{}

\section{Question 2: Assignment
Mechanism}\label{question-2-assignment-mechanism}

\subsection{(a)}\label{a}

Let \(D_i\) denote the treatment indicator, where

\[
D_i =
\begin{cases}
1 & \text{if individual } i \text{ attends college},\\
0 & \text{otherwise}.
\end{cases}
\]

Let \(Y_{1i}\) denote the potential income of individual \(i\) if they
attend college, and let \(Y_{0i}\) denote the potential income if they
do not attend college. The observed outcome is therefore

\[
Y_i = D_iY_{1i} + (1-D_i)Y_{0i}.
\]

The observed raw mean difference is

\[
E(Y_i \mid D_i = 1) - E(Y_i \mid D_i = 0).
\]

Using potential outcomes, this can be written as

\[
E(Y_{1i} \mid D_i = 1) - E(Y_{0i} \mid D_i = 0).
\]

Adding and subtracting \(E(Y_{0i} \mid D_i = 1)\) gives

\[
E(Y_{1i} \mid D_i = 1) - E(Y_{0i} \mid D_i = 0)
\]

\[
=
\underbrace{E(Y_{1i} - Y_{0i} \mid D_i = 1)}_{\text{ATET}}
+
\underbrace{E(Y_{0i} \mid D_i = 1) - E(Y_{0i} \mid D_i = 0)}_{\text{Selection bias}}.
\]

The first term is the average treatment effect on the treated. The
second term captures whether college attendees and non-attendees would
have had different incomes even in the absence of college attendance.

\subsection{(b)}\label{b}

\(\hat{\beta}_1\) does not necessarily measures the causal effect of
college attendance on income. The reason is that college attendance is
unlikely to be randomly assigned. Individuals who attend college may
differ systematically from non-attendees in characteristics that also
affect future income, such as household income, ability, motivation, or
family background. Therefore, the error term \(u_i\) may contain omitted
determinants of income that are correlated with \(college_i\). Formally,
this means

\[
E(u_i \mid college_i) \neq 0.
\]

As a result, the OLS estimate \(\hat{\beta}_1\) is likely biased and
captures both the causal effect of college attendance and selection
bias.

\subsection{(c)}\label{c}

A key observed driver of selection into college is household income,
\(hhincome_i\). Students from higher-income households may be more
likely to attend college because they face fewer financial constraints
and may have better access to educational resources. At the same time,
household income may also be correlated with future income through
family background, networks, school quality, or other socioeconomic
advantages. Therefore, \(hhincome_i\) can affect both college attendance
and later income, making it a plausible source of selection bias.

\subsection{(d)}\label{d}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Regression without controls}
\NormalTok{ols\_simple }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(income }\SpecialCharTok{\textasciitilde{}}\NormalTok{ college, }\AttributeTok{data =}\NormalTok{ data\_clean)}

\CommentTok{\# Regression with observed controls}
\NormalTok{ols\_controls }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(income }\SpecialCharTok{\textasciitilde{}}\NormalTok{ college }\SpecialCharTok{+}\NormalTok{ hhincome }\SpecialCharTok{+}\NormalTok{ race }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(year),}
                   \AttributeTok{data =}\NormalTok{ data\_clean)}

\FunctionTok{summary}\NormalTok{(ols\_simple)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = income ~ college, data = data_clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -83.967 -21.572  -2.351  19.278 163.672 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  96.2043     0.4591  209.56   <2e-16 ***
## college      41.5111     0.5344   77.68   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 30.6 on 16960 degrees of freedom
## Multiple R-squared:  0.2624, Adjusted R-squared:  0.2624 
## F-statistic:  6034 on 1 and 16960 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(ols\_controls)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = income ~ college + hhincome + race + factor(year), 
##     data = data_clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.622 -12.326  -0.022  12.195  61.064 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(>|t|)    
## (Intercept)      49.922566   0.392242  127.28   <2e-16 ***
## college          28.390518   0.293307   96.79   <2e-16 ***
## hhincome          0.776113   0.004202  184.68   <2e-16 ***
## race             -6.634654   0.367002  -18.08   <2e-16 ***
## factor(year)2010 -3.799309   0.251738  -15.09   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 16.39 on 16957 degrees of freedom
## Multiple R-squared:  0.7885, Adjusted R-squared:  0.7884 
## F-statistic: 1.58e+04 on 4 and 16957 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Compare the estimated coefficient on college}
\NormalTok{coef\_comparison }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Model =} \FunctionTok{c}\NormalTok{(}\StringTok{"Without controls"}\NormalTok{, }\StringTok{"With controls"}\NormalTok{),}
  \AttributeTok{College\_coefficient =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{coef}\NormalTok{(ols\_simple)[}\StringTok{"college"}\NormalTok{],}
    \FunctionTok{coef}\NormalTok{(ols\_controls)[}\StringTok{"college"}\NormalTok{]}
\NormalTok{  )}
\NormalTok{)}

\NormalTok{coef\_comparison}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 2
##   Model            College_coefficient
##   <chr>                          <dbl>
## 1 Without controls                41.5
## 2 With controls                   28.4
\end{verbatim}

The estimated coefficient on \(college_i\) falls once household income,
race, and year are added as controls. In the simple regression, the
coefficient is approximately \(41.51\), while in the controlled
regression it decreases to approximately \(28.39\). This suggests that
part of the raw difference in income was due to observable differences
between college and non-college individuals, rather than college
attendance itself. However, adding these controls only addresses
selection on observables. The estimate can still be biased if unobserved
factors, such as ability, motivation, parental education, or school
quality, affect both college attendance and later income. Therefore, the
controlled OLS estimate is more credible than the raw comparison, but it
still does not necessarily identify the causal effect of college
attendance.

\subsection{(e)}\label{e}

If scholarship amounts are randomly assigned, then scholarship variation
is independent of students' potential outcomes and pre-existing
characteristics. Therefore, students receiving higher and lower
scholarships should be comparable on average in terms of ability,
motivation, family background, and other determinants of future income.

In terms of the decomposition from part (a), random assignment implies
that the counterfactual income without college is the same across
treatment groups:

\[
E(Y_{0i} \mid D_i = 1) = E(Y_{0i} \mid D_i = 0).
\]

Therefore, the selection bias term,

\[
E(Y_{0i} \mid D_i = 1) - E(Y_{0i} \mid D_i = 0),
\]

equals zero. The remaining observed difference can then be interpreted
causally, for the variation in college attendance induced by the
randomized scholarship.

\subsection{(f)}\label{f}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lfe)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: Matrix
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'Matrix'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:tidyr':
## 
##     expand, pack, unpack
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# OLS with controls for comparison}
\NormalTok{ols\_controls }\OtherTok{\textless{}{-}} \FunctionTok{felm}\NormalTok{(income }\SpecialCharTok{\textasciitilde{}}\NormalTok{ college }\SpecialCharTok{+}\NormalTok{ hhincome }\SpecialCharTok{+}\NormalTok{ race }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(year),}
                     \AttributeTok{data =}\NormalTok{ data\_clean)}

\FunctionTok{summary}\NormalTok{(ols\_controls, }\AttributeTok{robust =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
##    felm(formula = income ~ college + hhincome + race + factor(year),      data = data_clean) 
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -42.622 -12.326  -0.022  12.195  61.064 
## 
## Coefficients:
##                   Estimate Robust s.e t value Pr(>|t|)    
## (Intercept)      49.922566   0.398709  125.21   <2e-16 ***
## college          28.390518   0.288967   98.25   <2e-16 ***
## hhincome          0.776113   0.004208  184.42   <2e-16 ***
## race             -6.634654   0.372167  -17.83   <2e-16 ***
## factor(year)2010 -3.799309   0.251761  -15.09   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 16.39 on 16957 degrees of freedom
## Multiple R-squared(full model): 0.7885   Adjusted R-squared: 0.7884 
## Multiple R-squared(proj model): 0.7885   Adjusted R-squared: 0.7884 
## F-statistic(full model, *iid*):1.58e+04 on 4 and 16957 DF, p-value: < 2.2e-16 
## F-statistic(proj model): 1.544e+04 on 4 and 16957 DF, p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# First stage: effect of scholarship on college attendance}
\NormalTok{first\_stage }\OtherTok{\textless{}{-}} \FunctionTok{felm}\NormalTok{(college }\SpecialCharTok{\textasciitilde{}}\NormalTok{ scholarship }\SpecialCharTok{+}\NormalTok{ hhincome }\SpecialCharTok{+}\NormalTok{ race }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(year),}
                    \AttributeTok{data =}\NormalTok{ data\_clean)}

\FunctionTok{summary}\NormalTok{(first\_stage, }\AttributeTok{robust =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
##    felm(formula = college ~ scholarship + hhincome + race + factor(year),      data = data_clean) 
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.0510 -0.5441  0.1992  0.2989  0.5417 
## 
## Coefficients:
##                    Estimate Robust s.e t value Pr(>|t|)    
## (Intercept)       3.227e-01  1.516e-02  21.287   <2e-16 ***
## scholarship       9.771e-03  5.576e-04  17.523   <2e-16 ***
## hhincome          2.808e-03  9.203e-05  30.513   <2e-16 ***
## race             -1.519e-02  1.023e-02  -1.485    0.138    
## factor(year)2010  4.774e-03  6.532e-03   0.731    0.465    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.4253 on 16957 degrees of freedom
## Multiple R-squared(full model): 0.06477   Adjusted R-squared: 0.06455 
## Multiple R-squared(proj model): 0.06477   Adjusted R-squared: 0.06455 
## F-statistic(full model, *iid*):293.6 on 4 and 16957 DF, p-value: < 2.2e-16 
## F-statistic(proj model): 375.1 on 4 and 16957 DF, p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# IV / 2SLS using scholarship as an instrument for college}
\NormalTok{iv\_model }\OtherTok{\textless{}{-}} \FunctionTok{felm}\NormalTok{(income }\SpecialCharTok{\textasciitilde{}}\NormalTok{ hhincome }\SpecialCharTok{+}\NormalTok{ race }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(year) }\SpecialCharTok{|}
                   \DecValTok{0} \SpecialCharTok{|}
\NormalTok{                   (college }\SpecialCharTok{\textasciitilde{}}\NormalTok{ scholarship),}
                 \AttributeTok{data =}\NormalTok{ data\_clean)}

\FunctionTok{summary}\NormalTok{(iv\_model, }\AttributeTok{robust =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
##    felm(formula = income ~ hhincome + race + factor(year) | 0 |      (college ~ scholarship), data = data_clean) 
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -43.978 -12.913  -0.065  12.679  59.721 
## 
## Coefficients:
##                   Estimate Robust s.e t value Pr(>|t|)    
## (Intercept)      53.726648   1.230575   43.66   <2e-16 ***
## hhincome          0.796485   0.007518  105.94   <2e-16 ***
## race             -6.741963   0.388125  -17.37   <2e-16 ***
## factor(year)2010 -3.762430   0.256458  -14.67   <2e-16 ***
## `college(fit)`   21.080628   2.244889    9.39   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 16.69 on 16957 degrees of freedom
## Multiple R-squared(full model): 0.7807   Adjusted R-squared: 0.7807 
## Multiple R-squared(proj model): 0.7807   Adjusted R-squared: 0.7807 
## F-statistic(full model, *iid*):1.301e+04 on 4 and 16957 DF, p-value: < 2.2e-16 
## F-statistic(proj model): 1.289e+04 on 4 and 16957 DF, p-value: < 2.2e-16 
## F-statistic(endog. vars):88.18 on 1 and 16957 DF, p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(ols\_controls)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      (Intercept)          college         hhincome             race 
##       49.9225665       28.3905181        0.7761129       -6.6346536 
## factor(year)2010 
##       -3.7993090
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(iv\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      (Intercept)         hhincome             race factor(year)2010 
##       53.7266476        0.7964851       -6.7419634       -3.7624299 
##   `college(fit)` 
##       21.0806278
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(iv\_model))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "(Intercept)"      "hhincome"         "race"             "factor(year)2010"
## [5] "`college(fit)`"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{iv\_college\_name }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(iv\_model))[}\FunctionTok{grepl}\NormalTok{(}\StringTok{"college"}\NormalTok{, }\FunctionTok{names}\NormalTok{(}\FunctionTok{coef}\NormalTok{(iv\_model)))]}
\NormalTok{iv\_college\_coef }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(iv\_model)[iv\_college\_name]}

\NormalTok{coef\_comparison }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Model =} \FunctionTok{c}\NormalTok{(}\StringTok{"OLS with controls"}\NormalTok{, }\StringTok{"IV / 2SLS"}\NormalTok{),}
  \AttributeTok{College\_coefficient =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{coef}\NormalTok{(ols\_controls)[}\StringTok{"college"}\NormalTok{],}
\NormalTok{    iv\_college\_coef}
\NormalTok{  )}
\NormalTok{)}

\NormalTok{coef\_comparison}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 2
##   Model             College_coefficient
##   <chr>                           <dbl>
## 1 OLS with controls                28.4
## 2 IV / 2SLS                        21.1
\end{verbatim}

In the first stage, \(scholarship_i\) is positively and significantly
related to college attendance. The coefficient is approximately
\(0.0098\), meaning that an additional 1,000 USD in scholarship support
increases the probability of attending college by about 0.98 percentage
points, conditional on household income, race, and year. The first-stage
\(F\)-statistic is well above 10, so the instrument is relevant.

The IV estimate of the effect of college on income is approximately
\(21.08\), compared to \(28.39\) in the controlled OLS regression. Since
scholarship amounts are randomly assigned, the independence assumption
is more credible. However, a causal interpretation still requires the
exclusion restriction: scholarships must affect later income only
through college attendance. Under this assumption, the IV estimate can
be interpreted as a causal LATE for compliers.

\section{Question 3: Effect
Heterogeneity}\label{question-3-effect-heterogeneity}

\subsection{(a)}\label{a-1}

The regression equation is

\[
income_i = \beta_0 + \beta_1 college_i + \beta_2 white_i
+ \beta_3(college_i \times white_i) + u_i,
\]

where \(white_i = 1\) for white individuals and \(white_i = 0\)
otherwise.

Here, \(\beta_1\) measures the college income premium for non-white
individuals. The coefficient \(\beta_3\) captures treatment effect
heterogeneity by race. It measures how much the college income premium
differs for white individuals relative to non-white individuals.
Therefore, the marginal effect of college is

\[
\beta_1
\]

for non-white individuals, and

\[
\beta_1 + \beta_3
\]

for white individuals. If \(\beta_3 = 0\), there is no difference in the
college income premium across race groups.

\subsection{(b)}\label{b-1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Make sure the race group is coded as white = 1 and white = 0 otherwise}
\NormalTok{data\_clean }\OtherTok{\textless{}{-}}\NormalTok{ data\_clean }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{white =}\NormalTok{ race)}

\CommentTok{\# Estimate the interaction model from Question 3(a)}
\NormalTok{heterogeneity\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(income }\SpecialCharTok{\textasciitilde{}}\NormalTok{ college }\SpecialCharTok{*}\NormalTok{ white, }\AttributeTok{data =}\NormalTok{ data\_clean)}

\CommentTok{\# Show full regression output}
\FunctionTok{summary}\NormalTok{(heterogeneity\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = income ~ college * white, data = data_clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -85.830 -19.491  -1.656  17.373 158.741 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     76.498      0.826  92.609   <2e-16 ***
## college         38.025      1.026  37.048   <2e-16 ***
## white           26.949      0.966  27.899   <2e-16 ***
## college:white    1.174      1.176   0.999    0.318    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 28.54 on 16958 degrees of freedom
## Multiple R-squared:  0.3584, Adjusted R-squared:  0.3583 
## F-statistic:  3157 on 3 and 16958 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Show a cleaner coefficient table}
\NormalTok{coef\_table\_3b }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(heterogeneity\_model)}\SpecialCharTok{$}\NormalTok{coefficients}

\FunctionTok{round}\NormalTok{(coef\_table\_3b, }\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Estimate Std. Error t value Pr(>|t|)
## (Intercept)     76.497      0.826  92.609    0.000
## college         38.025      1.026  37.048    0.000
## white           26.949      0.966  27.899    0.000
## college:white    1.174      1.176   0.999    0.318
\end{verbatim}

The regression from part (a) is estimated by OLS. The interaction term
\(college_i \times white_i\) is included to allow the return to college
to differ between white and non-white individuals.

\subsection{(c)}\label{c-1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Extract coefficients}
\NormalTok{beta\_1 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(heterogeneity\_model)[}\StringTok{"college"}\NormalTok{]}
\NormalTok{beta\_3 }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(heterogeneity\_model)[}\StringTok{"college:white"}\NormalTok{]}

\CommentTok{\# Marginal effects of college by race group}
\NormalTok{effect\_nonwhite }\OtherTok{\textless{}{-}}\NormalTok{ beta\_1}
\NormalTok{effect\_white }\OtherTok{\textless{}{-}}\NormalTok{ beta\_1 }\SpecialCharTok{+}\NormalTok{ beta\_3}

\NormalTok{effects\_by\_race }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Group =} \FunctionTok{c}\NormalTok{(}\StringTok{"white != 1"}\NormalTok{, }\StringTok{"white == 1"}\NormalTok{),}
  \AttributeTok{Marginal\_effect\_college =} \FunctionTok{c}\NormalTok{(effect\_nonwhite, effect\_white)}
\NormalTok{)}
 \FunctionTok{print}\NormalTok{(effects\_by\_race)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 2 x 2
##   Group      Marginal_effect_college
##   <chr>                        <dbl>
## 1 white != 1                    38.0
## 2 white == 1                    39.2
\end{verbatim}

The estimated marginal effect of college attendance is approximately
\(38.03\) for individuals with \(white_i \neq 1\). For individuals with
\(white_i = 1\), the estimated marginal effect is

\[
\hat{\beta}_1 + \hat{\beta}_3 = 38.03 + 1.17 = 39.20.
\]

Since income is measured in 1,000 USD, this means that college
attendance is associated with approximately 38,030 USD higher income for
non-white individuals and approximately 39,200 USD higher income for
white individuals.

\subsection{(d)}\label{d-1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Extract interaction coefficient and p{-}value}
\NormalTok{interaction\_result }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(heterogeneity\_model)}\SpecialCharTok{$}\NormalTok{coefficients[}\StringTok{"college:white"}\NormalTok{, ]}

\NormalTok{interaction\_result}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Estimate Std. Error    t value   Pr(>|t|) 
##  1.1744234  1.1760740  0.9985965  0.3180044
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Cleaner output}
\FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Coefficient =} \StringTok{"college:white"}\NormalTok{,}
  \AttributeTok{Estimate =}\NormalTok{ interaction\_result[}\StringTok{"Estimate"}\NormalTok{],}
  \AttributeTok{Std\_Error =}\NormalTok{ interaction\_result[}\StringTok{"Std. Error"}\NormalTok{],}
  \AttributeTok{t\_value =}\NormalTok{ interaction\_result[}\StringTok{"t value"}\NormalTok{],}
  \AttributeTok{p\_value =}\NormalTok{ interaction\_result[}\StringTok{"Pr(\textgreater{}|t|)"}\NormalTok{]}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 5
##   Coefficient   Estimate Std_Error t_value p_value
##   <chr>            <dbl>     <dbl>   <dbl>   <dbl>
## 1 college:white     1.17      1.18   0.999   0.318
\end{verbatim}

The difference in the college income premium across race groups is
captured by the interaction coefficient \(\beta_3\) on
\(college_i \times white_i\). The estimated interaction coefficient is
approximately \(1.17\), with a p-value of approximately \(0.318\).
Therefore, we do not reject

\[
H_0: \beta_3 = 0.
\]

This means that the estimated college premium is slightly higher for
white individuals, but the difference is not statistically significant.
Hence, the data do not provide strong evidence that the return to
college differs across race groups.

\section{Question 4: Probit and Logit
Models}\label{question-4-probit-and-logit-models}

\subsection{(a)}\label{a-2}

A limitation of using OLS when the dependent variable is binary is that
the fitted values are interpreted as predicted probabilities, but OLS
does not restrict them to lie between 0 and 1. Therefore, the model may
predict probabilities below 0 or above 1, which has no meaningful
probability interpretation. This is why logit and probit models are
often preferred for binary outcomes.

\subsection{(b)}\label{b-2}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Probit model}
\NormalTok{probit\_model }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}
\NormalTok{  college }\SpecialCharTok{\textasciitilde{}}\NormalTok{ hhincome }\SpecialCharTok{+}\NormalTok{ race,}
  \AttributeTok{data =}\NormalTok{ data\_clean,}
  \AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"probit"}\NormalTok{)}
\NormalTok{)}

\FunctionTok{summary}\NormalTok{(probit\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = college ~ hhincome + race, family = binomial(link = "probit"), 
##     data = data_clean)
## 
## Coefficients:
##               Estimate Std. Error z value Pr(>|z|)    
## (Intercept) -0.0761256  0.0281037  -2.709 0.006754 ** 
## hhincome     0.0102740  0.0003923  26.190  < 2e-16 ***
## race        -0.1031611  0.0298313  -3.458 0.000544 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 19509  on 16961  degrees of freedom
## Residual deviance: 18599  on 16959  degrees of freedom
## AIC: 18605
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Logit model}
\NormalTok{logit\_model }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(}
\NormalTok{  college }\SpecialCharTok{\textasciitilde{}}\NormalTok{ hhincome }\SpecialCharTok{+}\NormalTok{ race,}
  \AttributeTok{data =}\NormalTok{ data\_clean,}
  \AttributeTok{family =} \FunctionTok{binomial}\NormalTok{(}\AttributeTok{link =} \StringTok{"logit"}\NormalTok{)}
\NormalTok{)}

\FunctionTok{summary}\NormalTok{(logit\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = college ~ hhincome + race, family = binomial(link = "logit"), 
##     data = data_clean)
## 
## Coefficients:
##               Estimate Std. Error z value Pr(>|z|)    
## (Intercept) -0.1595936  0.0470184  -3.394 0.000688 ***
## hhincome     0.0174608  0.0006918  25.241  < 2e-16 ***
## race        -0.1818471  0.0493656  -3.684 0.000230 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 19509  on 16961  degrees of freedom
## Residual deviance: 18612  on 16959  degrees of freedom
## AIC: 18618
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

The probit and logit models give the same qualitative result. In both
models, the coefficient on \(hhincome_i\) is positive and statistically
significant. This suggests that individuals from higher-income
households are more likely to attend college.

The coefficient on \(race_i\) is negative and statistically significant
in both models. This means that individuals with \(race_i = 1\) have a
lower predicted probability of attending college, conditional on
household income.

The logit coefficients are larger in absolute value than the probit
coefficients because the two models use different link functions and are
measured on different scales. Therefore, the raw coefficient sizes
should not be interpreted directly as changes in probability. However,
both models agree on the direction of the effects.

\section{Question 5: Marginal
Effects}\label{question-5-marginal-effects}

\subsection{(a)}\label{a-3}

\subsection{(b)}\label{b-3}

\subsection{(c)}\label{c-2}

\end{document}
