---
title: "Assignment 2"
author: "Aleksandar Maric, Akando Räderer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(dplyr)
library(ggplot2)
```
# Assignment 2

## Exercise 1: Data preparation

### 1. 
At first we read-in the `.csv` files with `read.csv`. After a look at both datasets, we observe that `data_cleaned` is ready to go. However in `data_surnames` there is one row for Sri Lanka, which we will filter out.

```{r}
data_cleaned <- read.csv("data/ps2_cantons_cleaned.csv")
data_surnames <- read.csv("data/ps2_cantons_surnames.csv")

data_surnames

skimr::skim(data_cleaned)


data_surnames <- data_surnames |> filter(canton != "Sri Lanka")
```

Then we need to create the new variable `surname` and then drop the existing variables for `share_mueller`and `share_maier`. 

```{r}
data_surnames <- data_surnames |> mutate(surname=share_mueller+share_maier) |> 
  select(-share_mueller, -share_maier)

data_surnames
```

